# Generated by Django 2.2.11 on 2020-12-24 06:43

from django.db import migrations, models


def add_defaults(apps, schema_editor):
    # A few GroupRollPlayerResult.objects.create()
    GroupRollPlayerResult = apps.get_model("stat_checks", "GroupRollPlayerResult")
    GroupRollPlayerResult.objects.create(
        name="a little",
        value=0,
        template="{% if botch %} {{ botch|title }}! {% endif %}{{character}} contributes only |512{{result}}|n.",
    )
    GroupRollPlayerResult.objects.create(
        name="some progress",
        value=30,
        template="{{character}} contributes |240{{result}}|n to the task|n.",
    )
    GroupRollPlayerResult.objects.create(
        name="well",
        value=60,
        template="{{character}} contributes |g{{result}}|n to the task|n.",
    )
    GroupRollPlayerResult.objects.create(
        name="greatly",
        value=100,
        template="{{character}} contributes |542{{result}}|n to the task|n!",
    )
    GroupRollPlayerResult.objects.create(
        name="an impressive amount",
        value=150,
        template="{% if crit %} {{ crit|title }}! {% endif %}{{character}} contributes |355{{result}}|n to the task|n!",
    )

    # A few GroupRollRating.objects.create()
    GroupRollRating = apps.get_model("stat_checks", "GroupRollRating")
    GroupRollRating.objects.create(
        name="basic", value=0, template="They complete a |240{{result}}|n task."
    )
    GroupRollRating.objects.create(
        name="strenuous", value=100, template="They complete a |240{{result}}|n task."
    )
    GroupRollRating.objects.create(
        name="difficult", value=250, template="They complete a |g{{result}}|n task!"
    )
    GroupRollRating.objects.create(
        name="daunting", value=400, template="They complete a |g{{result}}|n task!"
    )
    GroupRollRating.objects.create(
        name="monumental", value=550, template="They complete a |542{{result}}|n task!"
    )
    GroupRollRating.objects.create(
        name="mythical", value=700, template="They complete a |m{{result}}|n task!!"
    )
    GroupRollRating.objects.create(
        name="LEGENDARY",
        value=900,
        template="They complete a |355{{result}}|n task!!! You may never see the like again...",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stat_checks", "0002_auto_20201025_1127"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupRollPlayerResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "value",
                    models.SmallIntegerField(
                        unique=True,
                        verbose_name="minimum value for this difficulty range/rating",
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="A jinja2 template string that will be output with the message for this result."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupRollRating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "value",
                    models.SmallIntegerField(
                        unique=True,
                        verbose_name="minimum value for this difficulty range/rating",
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="A jinja2 template string that will be output with the message for this result. 'result' is the context variable for the render: eg: 'a/an {{result}} task'"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        # Add default models to the database.
        migrations.RunPython(add_defaults, migrations.RunPython.noop, elidable=False),
    ]
