"""
settings.models

This file covers all the models (current and future) that are utilized by the
settings command.
"""


import re
from typing import Any, Generator, NamedTuple, TypeVar, Tuple, cast

from django.core.exceptions import FieldDoesNotExist, ValidationError
from django.core.validators import RegexValidator
from django.db import models
from evennia.utils.ansi import raw
from evennia.utils.evtable import EvTable
from evennia.utils.idmapper.models import SharedMemoryModel


class SettingsError(Exception):
    pass


class SettingTuple(NamedTuple):
    name: str
    category: str
    help_text: str
    value: object


# TODO: use a RegexValidator for this?
def nyi_validate_color(value):
    # TODO: This needs regex for foreground and background both.
    # bleh
    ansi_mode = r"([{|]\*)+([{|]u)+"
    ansi_fg = r"[{|][rgybmcwxRGYBMCWX]"
    ansi_bg = r"[{|]\[[rgybmcwx]"
    xterm256_fg = r"[{|][0-5]{3}|[{|]=[a-z]"
    xterm256_bg = r"[{|]\[[RGYBMCWX]|[{|]\[[0-5]{3}|[{|]\[=[a-z]"

    # TODO: Should this involve @options?
    fg_regex = "" if True else ""
    bg_regex = "" if True else ""


class ColorCode:
    fg: str
    bg: str

    ansi_mode = r"([{|]\*)+([{|]u)+"
    ansi_fg = r"[{|][rgybmcwxRGYBMCWX]"
    ansi_bg = r"[{|]\[[rgybmcwx]"
    xterm256_fg = r"[{|][0-5]{3}|[{|]=[a-z]"
    xterm256_bg = r"[{|]\[[RGYBMCWX]|[{|]\[[0-5]{3}|[{|]\[=[a-z]"

    fg_regex = ansi_mode + f"({ansi_fg}|{xterm256_fg})"
    bg_regex = ansi_mode + f"({ansi_bg}|{xterm256_bg})"

    fg_compile = re.compile(fg_regex)
    bg_compile = re.compile(bg_regex)

    def __init__(self, raw_string):
        fg_match = self.fg_compile.match(raw_string)
        bg_match = self.bg_compile.match(raw_string)

        self.fg = fg_match.group() if fg_match else ""
        self.bg = bg_match.group() if bg_match else ""

    def __str__(self):
        return f"{self.fg}{self.bg}"


class SettingsModelBase(SharedMemoryModel):
    class Meta:
        abstract = True

    def get_table(self):
        raise NotImplementedError

    def get_field(self, field_name: str):
        """
        Returns the django field for the input field name.
        """
        return self._meta.get_field(field_name)

    def get_fields(self):
        """
        Returns all the django fields set up on this category.
        """
        return self._meta.get_fields()


_SettingsCategoryT = TypeVar("_SettingsCategoryT", bound="SettingsCategoryBase")


class SettingsCategoryBase(SettingsModelBase):
    class Meta:
        abstract = True

    # The category's full name.  Displayed as a subheader in tables.
    category: str = "Unknown"

    # The category's abbreviated name.  Displayed in a column in tables.
    brief_category: str = "unknown"

    # Non-setting fields; exclude from tables and copying.  Set this for fields
    # that players shouldn't be aware of, such as relations to other models.
    exclude: Tuple[str] = ()

    # Settings that contain color codes.  Set this for fields that need
    # to display additional text to the caller to show what color
    # code is set.  Otherwise, Evennia will parse the value and it will not
    # display properly in the EvTable generated by get_table().
    color_settings: Tuple[str] = ()

    def __str__(self) -> str:
        return f"{self.category} Settings"

    def get_table(self) -> EvTable:
        """
        Returns an EvTable containing the category as a header and its
        settings as the rows.
        """
        table = EvTable(
            f"|w{self.category}|n",
            "",
            "",
            header_line_char="-",
            valign="t",
        )

        # Add each setting to the table (that isn't excluded).
        for setting in self.settings():
            table.add_row(setting.name, setting.help_text, setting.value)

        # Reformat table as follows:
        # - Setting names are centered.
        # - Setting help_text/descriptions are width capped so there's no screen overflow.
        # - Setting values are centered.
        table.table[0].reformat(align="c")
        table.table[1].reformat(width=40)
        table.table[2].reformat(align="c")

        # - Column cells have a pad at the bottom except for the header and the
        #   last cell in each column.
        for column in table.table:
            column.reformat(pad_bottom=1)
            column.reformat_cell(0, pad_bottom=0)
            column.reformat_cell(table.nrows - 1, pad_bottom=0)

        return table

    def settings(self) -> Generator[SettingTuple, None, None]:
        """
        Yields each setting (as the Setting tuple) found in
        this category of settings.
        """
        for field in self.get_fields():
            if field.name in self.exclude:
                continue
            yield SettingTuple(
                field.name,
                self.brief_category,
                field.help_text,
                getattr(self, field.name),
            )

    def has_setting(self, setting_name: str) -> bool:
        """
        Returns whether a given setting exists in this category.
        """
        try:
            field = self.get_field(setting_name)
            # Excluded fields are not considered settings.
            if field.name in self.exclude:
                return False
            else:
                return True
        except FieldDoesNotExist:
            return False

    def get_setting(self, setting_name: str) -> SettingTuple:
        """
        Returns a specific setting and its data if it exists in this category.
        """
        if not self.has_setting(setting_name):
            raise SettingsError(f"invalid setting requested ({setting_name})")

        field = self.get_field(setting_name)
        value = getattr(self, field.name)

        return SettingTuple(field.name, self.brief_category, field.help_text, value)

    def get_setting_as_str(self, setting_name: str) -> str:
        """
        Returns the text value of the setting.  This method converts values
        of fields as follows:
        - bool -> On/Off (str)
        - color codes -> the color code, adjusted for parsing (str)
        """
        if not self.has_setting(setting_name):
            raise SettingsError(f"invalid setting requested ({setting_name})")

        value = getattr(self, setting_name)

        if isinstance(value, bool):
            return "On" if value else "Off"

        # TODO: Remove the "Color" part.
        # Until we upgrade to Evennia 1.0+, EvTable will almost completely
        # strip color codes from an ANSIString. Strings like
        # "|r||r" to show a literal red "|r" won't display until
        # the upgrade.
        if setting_name in self.color_settings:
            return f"{value}|||{value}"

        return str(value)

    def set_setting(self, setting_name: str, value: Any) -> None:
        if not self.has_setting(setting_name):
            raise SettingsError(
                f"set_setting(): invalid setting name ({self.category}/{setting_name}: {str(value)})"
            )

        try:
            setattr(self, setting_name, value)
            self.save()
        except ValidationError as error:
            raise SettingsError(error.message)

    # def copy_one(
    #     self: _SettingsCategoryT, other: _SettingsCategoryT, setting_name: str
    # ) -> None:
    #     """
    #     Copies the specified setting into other.
    #     """
    #     if self.category != other.category:
    #         raise SettingsError(
    #             f"copy_one(): category mismatch ({self.category} onto {other.category})"
    #         )

    #     if not self.has_setting(setting_name):
    #         raise SettingsError(f"setting not found ({setting_name})")

    #     # getattr() is used here to get the raw value of the field, so we don't get
    #     # the value that's converted for display in a table.
    #     value = getattr(self, setting_name)
    #     other.set_setting(setting_name, value)

    # def copy_all(self: _SettingsCategoryT, other: _SettingsCategoryT) -> None:
    #     """
    #     Copies the values of all non-excluded fields from self to other.
    #     """
    #     if self.category != other.category:
    #         raise SettingsError(
    #             f"copy_all(): category mismatch ({self.category} onto {other.category})"
    #         )

    #     fields = self.get_fields()

    #     for field in fields:
    #         # Do not copy excluded (non-setting) fields over.
    #         if field.name in self.exclude:
    #             continue

    #         # TODO: Exception safety!
    #         # Need to handle potential exceptions (ValidationError and SettingsError),
    #         # which shouldn't be possible if we're copying existing data that should
    #         # already be valid.
    #         value = getattr(self, field.name)
    #         other.set_setting(field.name, value)

    def copy_to(self: _SettingsCategoryT, other: _SettingsCategoryT) -> None:
        """Copies the values of each setting field found in self to other."""
        raise NotImplementedError

    def reset(self, setting_name: str):
        """
        Sets the given setting field to its default value.
        """
        raise NotImplementedError

    def reset_all(self):
        """
        Sets each setting field to that field's default value.
        """
        raise NotImplementedError


class CharacterSettings(SettingsModelBase):
    class Meta:
        verbose_name_plural = "Character Settings"

    character = models.OneToOneField(
        "objects.ObjectDB",
        on_delete=models.CASCADE,
        related_name="settings",
        editable=False,
        db_index=True,
        primary_key=True,
    )

    # related models
    # account -> AccountSettings
    # general -> GeneralSettings
    # comm -> CommSettings
    # rp -> RPSettings
    account: "AccountSettings"
    general: "GeneralSettings"
    comm: "CommSettings"
    rp: "RPSettings"

    def __str__(self) -> str:
        return f"Settings for {self.character}"

    # TODO: Make this a cached_property.
    @property
    def valid_categories(self):
        result = ("all",) + tuple(
            category.brief_category for category in self.categories()
        )
        return result

    def categories(self) -> Generator[SettingsCategoryBase, None, None]:
        """
        Yields each category instance.  Intended as shorthand for situations
        where a loop needs to iterate through every (sub)category.
        """
        yield self.account
        yield self.general
        yield self.comm
        yield self.rp

    def get_category(self, brief_category_name: str) -> SettingsCategoryBase:
        for category in self.categories():
            if category.brief_category == brief_category_name:
                return category

        raise SettingsError(
            f"invalid settings category requested ({brief_category_name})"
        )

    def get_table(self) -> EvTable:
        """
        Returns an EvTable containing each category as a "subheader" row
        with rows containing that category's settings, separated by borders.
        """
        all_table = EvTable(valign="t")

        # This keeps track of which rows will have pad_bottom=0 and border_bottom=1.
        # Have to do it this way because EvTable will apply settings
        # a little oddly when using add_row(); putting kwargs in the
        # first row you add creates an EvColumn with column-specific settings
        # that won't be overridden by reformat_cell() (EvColumn settings take
        # precedence over EvCell settings).
        subheader_rows = []

        # For each category:
        # - Add the category as a header row.
        # - Add the rows containing the category's fields/settings.
        for category in self.categories():
            all_table.add_row(f"|w{category.category}", "", "")

            for setting in category.settings():
                if setting.name in category.exclude:
                    continue
                all_table.add_row(setting.name, setting.help_text, setting.value)

            subheader_rows.append(all_table.nrows - 1)

        # Setting names and values are center-aligned.
        all_table.table[0].reformat(align="c", pad_bottom=1)
        all_table.table[1].reformat(width=40, pad_bottom=1)
        all_table.table[2].reformat(align="c", pad_bottom=1)

        # Format each "end of category" row to have no bottom padding
        # and a border at the bottom.
        for row in subheader_rows:
            for column in all_table.table:
                column.reformat_cell(row, pad_bottom=0, border_bottom=1)

        return all_table


class AccountSettings(SettingsCategoryBase):
    class Meta:
        verbose_name_plural = "Account Settings"

    category = "Account"
    brief_category = "account"
    exclude = ("account", "owner")

    account = models.OneToOneField(
        "accounts.AccountDB",
        on_delete=models.CASCADE,
        related_name="settings",
        editable=False,
    )

    owner = models.OneToOneField(
        CharacterSettings,
        on_delete=models.CASCADE,
        related_name="account",
        editable=False,
        primary_key=True,
    )

    # This setting (from the old @settings) applies only to messages sent to the ACCOUNT.
    # The tag is set on the account, so most times the setting won't apply.
    # As an example, spin up Local, turn this @settings on, and use @ooc.  Lots of newlines.
    apply_output_newline = models.BooleanField(
        help_text="Inserts a blank line after all output sent by the game.",
        default=False,
    )

    ### Settings for alt options. ###

    allow_alt_bbread = models.BooleanField(
        help_text="Allow your alts to read bboards exclusive to this character.",
        default=False,
    )

    ### Settings for text removal. ###

    strip_ansi_names = models.BooleanField(
        help_text="Remove ANSI colors from text.", default=False
    )

    strip_ascii_text = models.BooleanField(
        help_text="Remove text contained in ASCII tags.", default=False
    )

    def copy_to(self: "AccountSettings", other: "AccountSettings") -> None:
        other.apply_output_newline = self.apply_output_newline

        other.allow_alt_bbread = self.allow_alt_bbread

        other.strip_ansi_names = self.strip_ansi_names
        other.strip_ascii_text = self.strip_ascii_text


class GeneralSettings(SettingsCategoryBase):
    class Meta:
        verbose_name_plural = "General Settings"

    category = "General"
    brief_category = "general"
    exclude = ("owner",)

    owner = models.OneToOneField(
        CharacterSettings,
        on_delete=models.CASCADE,
        editable=False,
        primary_key=True,
        related_name="general",
    )

    ### Settings for gameplay modes. ###

    brief_mode = models.BooleanField(
        help_text="Do not display room descs when moving through rooms.",
        default=False,
    )
    private_mode = models.BooleanField(
        help_text="Arx will not log pages sent to this character.\nWARNING: Staff may not be able to assist you with harassment if this mode is enabled.",
        default=False,
    )
    verbose_where_mode = models.BooleanField(
        help_text="Display roomtitle information on where.", default=False
    )
    ic_only_mode = models.BooleanField(
        help_text="Receive only IC forms of communication (emits, messages).\nNOTE: This will prevent you from receiving ANY pages and notifies the sender you are IC only.",
        default=False,
    )

    ### Settings for game emits. ###

    show_model_emits = models.BooleanField(
        help_text="Receive an emit when a character models what they're wearing.",
        default=True,
    )
    show_weather_emits = models.BooleanField(
        help_text="Receive an emit when the weather changes.", default=True
    )

    def copy_to(self: "GeneralSettings", other: "GeneralSettings") -> None:
        """Copies all General settings fields from self to other."""
        other.brief_mode = self.brief_mode
        other.private_mode = self.private_mode
        other.verbose_where_mode = self.verbose_where_mode
        other.ic_only_mode = self.ic_only_mode

        other.show_model_emits = self.show_model_emits
        other.show_weather_emits = self.show_weather_emits


class RPSettings(SettingsCategoryBase):
    class Meta:
        verbose_name = "RP Settings"
        verbose_name_plural = "RP Settings"

    category = "RP"
    brief_category = "rp"
    exclude = ("owner",)
    color_settings = ("pose_quote_color", "pose_mention_color", "place_name_color")

    owner = models.OneToOneField(
        CharacterSettings,
        on_delete=models.CASCADE,
        editable=False,
        primary_key=True,
        related_name="rp",
    )

    ### Settings for emits and poses. ###

    apply_emit_label = models.BooleanField(
        help_text="Apply a label naming the author of an emit at the start of it.",
        default=False,
    )
    apply_pose_break = models.BooleanField(
        help_text="Apply a newline between poses.",
        default=False,
    )

    ### Settings for highlight colors. ###

    pose_quote_color = models.CharField(
        help_text="The color to highlight text within pose quotation marks.",
        max_length=20,
        default="|n",
    )
    pose_mention_color = models.CharField(
        help_text="The color to highlight your name when mentioned in poses.",
        max_length=20,
        default="|n",
    )

    ### Settings for places. ###

    place_name_color = models.CharField(
        help_text="The color to highlight the place name when the TT command is used at your place.",
        max_length=20,
        default="|n",
    )

    def copy_to(self: "RPSettings", other: "RPSettings") -> None:
        """Copies all RP settings fields from self to other."""
        other.apply_emit_label = self.apply_emit_label
        other.apply_pose_break = self.apply_pose_break

        other.pose_quote_color = self.pose_quote_color
        other.pose_mention_color = self.pose_mention_color

        other.place_name_color = self.place_name_color


class CommSettings(SettingsCategoryBase):
    class Meta:
        verbose_name = "Communication Settings"
        verbose_name_plural = "Communication Settings"

    category = "Communication"
    brief_category = "comm"
    exclude = ("owner",)

    owner = models.OneToOneField(
        CharacterSettings,
        on_delete=models.CASCADE,
        editable=False,
        primary_key=True,
        related_name="comm",
    )

    ### Settings for bboards. ###

    ### Settings for channels. ###

    highlight_chan_mention = models.BooleanField(
        help_text="Highlight your name when mentioned on a channel.", default=False
    )

    ### Settings for messengers. ###

    show_msg_text = models.BooleanField(
        help_text="Display the text of messages upon sending them.", default=False
    )
    show_msg_notice = models.BooleanField(
        help_text="Display the notification for pending messages.", default=True
    )
    show_msg_delivery = models.BooleanField(
        help_text="Display the notification for messenger deliveries.", default=True
    )

    def copy_to(self: "CommSettings", other: "CommSettings") -> None:
        """Copies all Communication settings fields from self to other."""
        other.highlight_chan_mention = self.highlight_chan_mention

        other.show_msg_text = self.show_msg_text
        other.show_msg_notice = self.show_msg_notice
        other.show_msg_delivery = self.show_msg_delivery
