"""
settings.models

This file covers all the models (current and future) that are utilized by the
settings command.
"""


import re
from typing import Any, Generator, List, NamedTuple, TypeVar

from django.core.exceptions import FieldDoesNotExist, ValidationError
from django.core.validators import RegexValidator
from django.db import models
from evennia.utils.ansi import raw
from evennia.utils.evtable import EvTable
from evennia.utils.idmapper.models import SharedMemoryModel


class SettingsError(Exception):
    pass


class Setting(NamedTuple):
    name: str
    category: str
    help_text: str
    value: object


# TODO: use a RegexValidator for this
def nyi_validate_color(value):
    # TODO: This needs regex for foreground and background both.
    # bleh
    ansi_mode = r"[{|][*u]"
    ansi_fg = r"[{|][rgybmcwxRGYBMCWX]"
    ansi_bg = r"[{|]\[[rgybmcwx]"
    xterm256_fg = r"[{|][0-5]{3}|[{|]=[a-z]"
    xterm256_bg = r"[{|]\[[0-5]{3}|[{|]\[=[a-z]"

    fg_regex = "" if True else ""
    bg_regex = "" if True else ""


class ColorCode:
    fg: str
    bg: str

    ansi_mode = r"([{|]\*)+([{|]u)+"
    ansi_fg = r"[{|][rgybmcwxRGYBMCWX]"
    ansi_bg = r"[{|]\[[rgybmcwx]"
    xterm256_fg = r"[{|][0-5]{3}|[{|]=[a-z]"
    xterm256_bg = r"[{|]\[[RGYBMCWX]|[{|]\[[0-5]{3}|[{|]\[=[a-z]"

    fg_regex = ansi_mode + f"({ansi_fg}|{xterm256_fg})"
    bg_regex = ansi_mode + f"({ansi_bg}|{xterm256_bg})"

    fg_compile = re.compile(fg_regex)
    bg_compile = re.compile(bg_regex)

    def __init__(self, raw_string):
        fg_match = self.fg_compile.match(raw_string)
        bg_match = self.bg_compile.match(raw_string)

        self.fg = fg_match.group() if fg_match else ""
        self.bg = bg_match.group() if bg_match else ""

    def __str__(self):
        return f"{self.fg}{self.bg}"


validate_color = RegexValidator(
    message="%(value)s is not a valid color code.  See 'help color' for codes."
)


class BaseSettings(SharedMemoryModel):
    class Meta:
        abstract = True

    def get_table(self):
        raise NotImplementedError("called abstract model's get_table() method")

    def get_field(self, field_name: str):
        """
        Returns the django field for the input field name.
        """
        return self._meta.get_field(field_name)

    def get_fields(self):
        """
        Returns all the django fields set up on this category.
        """
        return self._meta.get_fields()


class CategorySettings(BaseSettings):
    class Meta:
        abstract = True

    # The category's full name.  Displayed as a subheader in tables.
    category = "Unknown"
    # The category's abbreviated name.  Displayed in a column in tables.
    # This should match what's in PlayerSettings.valid_categories.
    brief_category = "unknown"
    # Non-setting fields; exclude from tables and copying.  Set this for fields
    # that players shouldn't modify, such as relations to other models.
    exclude = ("base",)
    # Settings consisting of color codes.  Indicates that these fields need
    # to display additional text to the caller to show what color
    # code is set.  Otherwise, Evennia will parse the value and it will not
    # display properly in the EvTable generated by get_table().
    color_settings = ()
    # The related name to refer to this category from the PlayerSettings
    # model that is referring to this category.
    related_name = "%(class)s"

    _Category = TypeVar("_Category", bound="CategorySettings")

    base: "PlayerSettings"

    base = models.OneToOneField(
        "PlayerSettings",
        on_delete=models.CASCADE,
        related_name=related_name,
        editable=False,
        primary_key=True,
    )

    def __str__(self) -> str:
        return f"{self.category} Settings for {self.base.character}"

    def has_setting(self, setting_name: str) -> bool:
        """
        Returns whether a given setting exists in this category.
        """
        try:
            field = self._meta.get_field(setting_name)
            # Excluded fields are not considered settings.
            if field.name in self.exclude:
                return False
            return True
        except FieldDoesNotExist:
            return False

    def get_setting(self, setting_name: str) -> Setting:
        """
        Returns a specific setting and its data if it exists in this category.
        """
        if not self.has_setting(setting_name):
            raise SettingsError(f"invalid setting requested ({setting_name})")

        field = self.get_field(setting_name)
        if field.name in self.exclude:
            raise SettingsError(
                f"excluded (non-setting) field requested ({setting_name})"
            )

        return Setting(
            field.name,
            self.brief_category,
            field.help_text,
            self.get_setting_value(setting_name),
        )

    def get_setting_value(self, setting_name: str) -> Any:
        """
        Returns the value of the setting.  This method converts values
        of fields as follows:
        - bool -> On/Off (str)
        - color codes -> "Color" prefixed by the code (str)
        """
        if not self.has_setting(setting_name):
            raise SettingsError(f"invalid setting requested ({setting_name})")

        value = getattr(self, setting_name)

        if isinstance(value, bool):
            return "On" if value else "Off"

        # TODO: Remove the "Color" part.
        # Until we upgrade to Evennia 1.0+, EvTable will almost completely
        # strip color codes from an ANSIString. Strings like
        # "|r||r" to show a literal red "|r" won't display until
        # the upgrade.
        if setting_name in self.color_settings:
            return f"{value}{raw(value)}Color"

        return value

    def settings(self) -> Generator[Setting, None, None]:
        """
        Yields each setting (as the Setting tuple) found in
        this category of settings.
        """
        for field in self.get_fields():
            if field.name in self.exclude:
                continue
            yield Setting(
                field.name,
                self.brief_category,
                field.help_text,
                self.get_setting_value(field.name),
            )

    def set_setting(self, setting_name: str, value: Any) -> None:
        if not self.has_setting(setting_name):
            raise SettingsError(
                f"attempted to modify invalid setting ({setting_name}: {value})"
            )

        try:
            setattr(self, setting_name, value)
            self.save()
        except ValidationError as error:
            raise SettingsError(error.message)

    def get_table(self) -> EvTable:
        """
        Returns an EvTable containing the category as a header and its
        settings as the rows.
        """
        fields = self.get_fields()

        table = EvTable(
            f"|w{self.category}|n",
            header_line_char="-",
            valign="t",
        )

        # Add to the table each field not specifically excluded from it.
        for field in fields:
            if field.name in self.exclude:
                continue

            value = self.get_setting(field.name)

            table.add_row(field.name, field.help_text, value)

        # Reformat table as follows:
        # - Settings names are centered.
        # - Setting descriptions are capped so there's no screen overflow.
        # - Setting values are centered.
        table.table[0].reformat(align="c")
        table.table[1].reformat(width=40)
        table.table[2].reformat(align="c")

        # - Column cells have a pad at the bottom except for the header and the
        #   last cell in each column.
        for column in table.table:
            column.reformat(pad_bottom=1)
            column.reformat_cell(0, pad_bottom=0)
            column.reformat_cell(table.nrows - 1, pad_bottom=0)

        return table

    def copy_one(self: _Category, other: _Category, setting_name: str) -> None:
        """
        Copies the specified setting into other.
        """
        if self.category != other.category:
            raise SettingsError(
                f"category mismatch when attempting to copy ({self.category} onto {other.category})"
            )

        if setting_name in self.exclude:
            raise SettingsError(f"cannot copy excluded settings ({setting_name})")

        if not self.has_setting(setting_name):
            raise SettingsError(f"setting not found ({setting_name})")

        value = getattr(self, setting_name)
        setattr(other, setting_name, value)
        other.save()

    def copy_all(self: _Category, other: _Category) -> None:
        """
        Copies the values of all non-excluded fields from self to other.
        """
        if self.category != other.category:
            raise SettingsError(
                f"category mismatch when attempting to copy ({self.category} onto {other.category})"
            )

        fields = self.get_fields()

        for field in fields:
            # Do NOT copy excluded fields over.
            if field.name in self.exclude:
                continue

            value = getattr(self, field.name)
            setattr(other, field.name, value)

        other.save()


class PlayerSettings(BaseSettings):
    class Meta:
        verbose_name = "Settings"
        verbose_name_plural = "Settings"

    valid_categories = ("all", "general", "rp", "comm")

    character = models.OneToOneField(
        "objects.ObjectDB",
        on_delete=models.CASCADE,
        related_name="settings",
        editable=False,
        db_index=True,
        primary_key=True,
    )

    # related models
    # general -> GeneralSettings
    # comm -> CommSettings
    # rp -> RPSettings
    # craft -> CraftSettings
    # bank -> BankSettings
    general: "GeneralSettings"
    comm: "CommSettings"
    rp: "RPSettings"
    # craft: "CraftSettings"
    # bank: "BankSettings"

    def __str__(self) -> str:
        return f"Settings for {self.character}"

    def get_category(self, category: str) -> CategorySettings:
        if category == "general":
            return self.general
        elif category == "comm":
            return self.comm
        elif category == "rp":
            return self.rp
        else:
            raise SettingsError(f"invalid category requested ({category})")

    def categories(self) -> Generator[CategorySettings, None, None]:
        """
        Yields each category instance.  Intended as shorthand for situations
        where a loop needs to iterate through every (sub)category.
        """
        yield self.general
        yield self.comm
        yield self.rp

    def get_table(self) -> EvTable:
        """
        Returns an EvTable containing each category as a "subheader" row
        with rows containing that category's settings, separated by borders.
        """
        all_table = EvTable(valign="t")

        category_models: List[CategorySettings] = [self.general, self.rp, self.comm]

        # This keeps track of which rows will have pad_bottom=0 and border_bottom=1.
        # Have to do it this way because EvTable will apply settings
        # a little oddly when using add_row(); putting kwargs in the
        # first row you add creates an EvColumn with column-specific settings
        # that won't be overridden by reformat_cell() (column settings take
        # precedence over cell settings).
        subheader_rows = []

        # For each category:
        # - Add the category as a header row.
        # - Add the rows containing the category's fields/settings.
        for category_model in category_models:
            all_table.add_row(f"|w{category_model.category}", "", "")

            fields = category_model.get_fields()

            for field in fields:
                if field.name in category_model.exclude:
                    continue
                value = category_model.get_setting(field.name)
                all_table.add_row(field.name, field.help_text, value)

            subheader_rows.append(all_table.nrows - 1)

        # Setting names and values are center-aligned.
        all_table.table[0].reformat(align="c", pad_bottom=1)
        all_table.table[1].reformat(width=40, pad_bottom=1)
        all_table.table[2].reformat(align="c", pad_bottom=1)

        # Format each "end of category" row to have no bottom padding
        # and a border at the bottom.
        for row in subheader_rows:
            for column in all_table.table:
                column.reformat_cell(row, pad_bottom=0, border_bottom=1)

        return all_table


class GeneralSettings(CategorySettings):
    class Meta:
        verbose_name = "General Settings"
        verbose_name_plural = "General Settings"

    category = "General"
    brief_category = "general"
    related_name = "general"

    ### Settings for gameplay modes. ###

    brief_mode = models.BooleanField(
        help_text="Do not display room descs when moving through rooms.",
        default=False,
    )
    private_mode = models.BooleanField(
        help_text="Arx will not log pages sent to this character.\nNOTE: Staff may not be able to assist you with harassment if this mode is enabled.",
        default=False,
    )
    verbose_where_mode = models.BooleanField(
        help_text="Display roomtitle information on where.", default=False
    )
    ic_only_mode = models.BooleanField(
        help_text="Receive only IC forms of communication (emits, messages).\nNOTE: This will prevent you from receiving ANY pages and notifies the sender you are IC only.",
        default=False,
    )

    ### Settings for text removal. ###

    strip_ansi_names = models.BooleanField(
        help_text="Remove ANSI colors from text.", default=False
    )

    strip_ascii_text = models.BooleanField(
        help_text="Remove text contained in ASCII tags.", default=False
    )

    ### Settings for game emits. ###

    show_model_emits = models.BooleanField(
        help_text="Receive an emit when a character models what they're wearing.",
        default=True,
    )
    show_weather_emits = models.BooleanField(
        help_text="Receive an emit when the weather changes.", default=True
    )

    ## Settings for miscellany. ###

    # This setting (from @settings) applies only to messages sent to the ACCOUNT.
    # The tag is set on the account, so most times the setting won't apply.
    # As an example, spin up Local, turn this @settings on, and use @ooc.  Lots of newlines.
    apply_output_newline = models.BooleanField(
        help_text="Applies a newline character to the end of output sent by the game.",
        default=False,
    )


class CommSettings(CategorySettings):
    class Meta:
        verbose_name = "Comm Settings"
        verbose_name_plural = "Comm Settings"

    category = "Communication"
    brief_category = "comm"
    related_name = "comm"

    ### Settings for bboards. ###

    allow_bb_altread = models.BooleanField(
        help_text="Allow your alts to read your bboards.",
        default=False,
    )

    ### Settings for channels. ###

    highlight_chan_mention = models.BooleanField(
        help_text="Highlight your name when mentioned on a channel.", default=False
    )

    ### Settings for messengers. ###

    show_msg_text = models.BooleanField(
        help_text="Display the text of messages upon sending them.", default=False
    )
    show_msg_notice = models.BooleanField(
        help_text="Display the notification for pending messages.", default=True
    )
    show_msg_delivery = models.BooleanField(
        help_text="Display the notification for messenger deliveries.", default=True
    )


class RPSettings(CategorySettings):
    class Meta:
        verbose_name = "RP Settings"
        verbose_name_plural = "RP Settings"

    category = "RP"
    brief_category = "rp"
    related_name = "rp"
    color_settings = ("pose_quote_color", "pose_mention_color", "place_name_color")

    ### Settings for emits and poses. ###

    apply_emit_label = models.BooleanField(
        help_text="Apply a label naming the author of an emit at the start of it.",
        default=False,
    )
    apply_pose_break = models.BooleanField(
        help_text="Apply a newline between poses.",
        default=False,
    )

    ### Settings for highlight colors. ###

    pose_quote_color = models.CharField(
        help_text="The color to highlight text within pose quotation marks.",
        max_length=20,
        default="|n",
    )
    pose_mention_color = models.CharField(
        help_text="The color to highlight your name when mentioned in poses.",
        max_length=20,
        default="|n",
    )

    ### Settings for places. ###

    place_name_color = models.CharField(
        help_text="The color to highlight the place name when the TT command is used at your place.",
        max_length=20,
        default="|n",
    )


# class CraftSettings(CategorySettings):
#     category = "Crafting"
#     brief_category = "craft"
#     related_name = "craft"

#     # TODO: Should I have ShopSettings with this in it?
#     # I think more db models need to exist before this is possible.  Namely:
#     # - DB listings of what a shop is
#     # - what room(s) comprise the shop
#     # - who owns the shop
#     # - the shop recipes, etc.
#     # shop_silver_minimum = models.PositiveIntegerField(
#     #     help_text="The minimum value of silver paid to a shop to generate an inform."
#     # )

#     def get_table(self):
#         table = EvTable(valign="t")

#         # TODO: Add the shop settings here.

#         return table


# class BankSettings(CategorySettings):
#     category = "Banking"
#     brief_category = "bank"
#     related_name = "bank"

#     # related models
#     # resources -> Manager?[BankResourceSetting]
#     # materials -> Manager?[BankMaterialSetting]

#     def get_table(self):
#         table = EvTable(valign="t")

#         # TODO: Add the resources and materials here.

#         return table


# class BankResourceSetting(SharedMemoryModel):
#     bank_setting = models.ForeignKey(
#         BankSettings, on_delete=models.CASCADE, related_name="resources"
#     )

#     # resource = models.OneToOneField("", on_delete=models.CASCADE, related_name="+")
#     threshold = models.PositiveIntegerField(blank=False, default=0)


# class BankMaterialSetting(SharedMemoryModel):
#     bank_setting = models.ForeignKey(
#         BankSettings, on_delete=models.CASCADE, related_name="materials"
#     )

#     # material = models.OneToOneField("", on_delete=models.CASCADE, related_name="+")
#     threshold = models.PositiveIntegerField(blank=False, default=0)
